cache:
  directories:
    - "$HOME"
language: python
python:
  - 2.7.8
  - 2.7
install:
  - travis_retry pip install coveralls flake8 -r requirements.txt
script:
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  - python setup.py test
  - coverage run --source=src setup.py test
after_success: coveralls
notifications:
  email:
    on_success: never
    on_failure: never
