# sudo: false
# cache:
#   directories:
#     - "$HOME"
language: python
matrix:
  include:
    # - python: 2.7.8
    #   dist: precise
    #   before_install: pip install --upgrade pip setuptools
    - python: 2.7
    - python: 3.7
  allow_failures:
    - python: 3.7
install:
  # - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_retry pip install -r requirements.txt ; fi
  # - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_retry pip install coveralls ; fi
  - travis_retry pip install coveralls -r requirements.txt
script:
  - coverage run --source=src setup.py test
  - flake8 *.py
  - flake8 src/wpsremote
  - flake8 test
after_success: coveralls
notifications:
  email:
    on_success: never
    on_failure: never
